### ISSUE TITLE
Stopped working with errors...

### ISSUE THREAD

**Issue by THX2112** [jrfernandes/ontario_energy_board#19]
Yo.

OEB integration stopped working yesterday. In the logs I see these errors:

```
Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for ontario_energy_board using this method at custom_components/ontario_energy_board/__init__.py, line 21: hass.config_entries.async_setup_platforms(entry, PLATFORMS)
9:05:32 AM – (WARNING) helpers/frame.py
Could not find energy rates for Energy Plus Inc. (RESIDENTIAL)
9:05:32 AM – (ERROR) Ontario Energy Board (custom integration)
```

Details:

```
This error originated from a custom integration.

Logger: custom_components.ontario_energy_board.coordinator
Source: custom_components/ontario_energy_board/coordinator.py:108
Integration: Ontario Energy Board (documentation, issues)
First occurred: 9:05:32 AM (1 occurrences)
Last logged: 9:05:32 AM

Could not find energy rates for Energy Plus Inc. (RESIDENTIAL)

```

Nothing was being done when it stopped working and I assumed it was just a connection error until I saw the second error about async. Might not be related though?

Rebooting, restarting, updating did nothing.

**Comment by jazzyisj** [comment]
The warning started when you updated to v2022.2 The integration hasn't stopped working (at least not because of this error).  Nothing has changed yet, you are seeing a warning that it well stop working in v2022.3.  I'm here to report the warning myself.  There are many integrations throwing a similar warning right now.  Anyway, I'm sure the dev will have it sorted by the next release.

**Comment by THX2112** [comment]
Regardless if that's the origin of the problem or not, it's still not fetching rates. Very suspicious that the problem started exactly when that error was first thrown. Could be coincidence though...

Still getting the error. Turned on debugging for the integration and caught a bunch of these:

```
2023-02-06 07:01:08.474 ERROR (MainThread) [custom_components.ontario_energy_board.coordinator] Could not find energy rates for Energy Plus Inc. (RESIDENTIAL)
2023-02-06 07:01:26.538 ERROR (MainThread) [custom_components.ontario_energy_board.coordinator] Could not find energy rates for Energy Plus Inc. (RESIDENTIAL)
```

I checked all the other logs and there were no related errors. Any ideas now to troubleshoot further? How can I tell if it's actually making a connection or if there's errors at the site?

**Comment by N3rdP1um23** [comment]
With the errors that you've shared, the plugin is unable to find `Energy Plus Inc. (RESIDENTIAL)` as a company listing from the OEB file the rates are pulled from. 

Looking at the file manually, that entry doesn't exist anymore (a company entry for `Energy Plus Inc. (RESIDENTIAL)`). All I can find is the following `GrandBridge Energy Inc.-Energy+ Rate Zone`. Looks like Energy Plus is no longer and has been renamed due to a name change, merger of companies, etc..

You should be able to find the new listing under `GrandBridge Energy Inc.-Energy+ Rate Zone` however. Hopefully that helps 🙂

**Comment by THX2112** [comment]
Hey, thanks for looking into this.

This was the problem.

There was no way to reconfigure and the plugin had to be uninstalled and reinstalled for the new service name to show up.
